// <auto-generated />
using MiLibreriaWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiLibreriaWebApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250828183528_SeedReadBooks")]
    partial class SeedReadBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MiLibreriaWebApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Fyodor Dostoevsky",
                            CountryId = 9,
                            GenreId = 1,
                            ISBN = "9780140449136",
                            ReadingStatus = 2,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Kennedy Toole",
                            CountryId = 3,
                            GenreId = 1,
                            ISBN = "9788433971802",
                            ReadingStatus = 2,
                            Title = "A Confederacy of Dunces"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Giuseppe Tomasi di Lampedusa",
                            CountryId = 23,
                            GenreId = 9,
                            ISBN = "9788435008910",
                            ReadingStatus = 2,
                            Title = "The Leopard"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            CountryId = 99,
                            GenreId = 2,
                            ISBN = "9780062316097",
                            ReadingStatus = 2,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Thomas Mann",
                            CountryId = 19,
                            GenreId = 1,
                            ISBN = "9788499893466",
                            ReadingStatus = 2,
                            Title = "The Magic Mountain"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Gaston Leroux",
                            CountryId = 22,
                            GenreId = 1,
                            ISBN = "9780141191508",
                            ReadingStatus = 2,
                            Title = "The Phantom of the Opera"
                        },
                        new
                        {
                            Id = 7,
                            Author = "H.G. Wells",
                            CountryId = 21,
                            GenreId = 5,
                            ISBN = "9780141439983",
                            ReadingStatus = 2,
                            Title = "The Invisible Man"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Mary Shelley",
                            CountryId = 21,
                            GenreId = 5,
                            ISBN = "9780141439471",
                            ReadingStatus = 2,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Robert Louis Stevenson",
                            CountryId = 21,
                            GenreId = 14,
                            ISBN = "9780141439822",
                            ReadingStatus = 2,
                            Title = "Treasure Island"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Edmund Burke",
                            CountryId = 21,
                            GenreId = 20,
                            ISBN = "9788498791749",
                            ReadingStatus = 2,
                            Title = "Reflections on the Revolution in France"
                        },
                        new
                        {
                            Id = 11,
                            Author = "María Elvira Roca Barea",
                            CountryId = 30,
                            GenreId = 20,
                            ISBN = "9788491640686",
                            ReadingStatus = 2,
                            Title = "Imperiofobia"
                        },
                        new
                        {
                            Id = 12,
                            Author = "George Orwell",
                            CountryId = 21,
                            GenreId = 1,
                            ISBN = "9788499890946",
                            ReadingStatus = 2,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 13,
                            Author = "George Orwell",
                            CountryId = 21,
                            GenreId = 1,
                            ISBN = "9788499890946",
                            ReadingStatus = 2,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 14,
                            Author = "José Saramago",
                            CountryId = 88,
                            GenreId = 1,
                            ISBN = "9788466368066",
                            ReadingStatus = 2,
                            Title = "Blindness"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Daron Acemoglu, James A. Robinson",
                            CountryId = 3,
                            GenreId = 2,
                            ISBN = "9780307719225",
                            ReadingStatus = 2,
                            Title = "Why Nations Fail"
                        });
                });

            modelBuilder.Entity("MiLibreriaWebApp.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "China"
                        },
                        new
                        {
                            Id = 2,
                            Name = "India"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 16,
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 21,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 22,
                            Name = "France"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 25,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 27,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 53,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 83,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 92,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Switzerland"
                        });
                });

            modelBuilder.Entity("MiLibreriaWebApp.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Children"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Graphic Novel"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Short Story"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Memoir"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Essay"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Critical Essay"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Literary Essay"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Philosophical Essay"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Scientific Essay"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Political Essay"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Travel Essay"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Personal Essay"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cookbook"
                        });
                });

            modelBuilder.Entity("MiLibreriaWebApp.Models.Book", b =>
                {
                    b.HasOne("MiLibreriaWebApp.Models.Country", "Country")
                        .WithMany("Books")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("MiLibreriaWebApp.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MiLibreriaWebApp.Models.Country", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MiLibreriaWebApp.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
